import type { Journey, JourneyPhase } from "./types";
import { getRealm } from "./realms";

// Default phase arc — can be overridden per journey
// Rotate an array so it starts at offset, wrapping around
function rotateArray<T>(arr: T[], offset: number): T[] {
  if (arr.length === 0) return arr;
  const o = offset % arr.length;
  return [...arr.slice(o), ...arr.slice(0, o)];
}

function defaultPhases(
  overrides: Partial<Record<string, Partial<JourneyPhase>>>
): JourneyPhase[] {
  const realm = overrides._realm as unknown as string | undefined;
  const realmData = realm ? getRealm(realm) : undefined;
  const allShaders = realmData?.shaderModes ?? ["ethereal", "sacred", "fractal", "cosmos"];

  const defaults: JourneyPhase[] = [
    {
      id: "threshold",
      start: 0.0,
      end: 0.15,
      shaderModes: rotateArray(allShaders, 0),
      shaderOpacity: 0.9,
      aiPrompt: "subtle darkness with faint emerging forms",
      aiPromptModifiers: {
        lowAmplitude: "near silence, barely visible",
      },
      denoisingRange: [0.3, 0.5],
      targetFps: 0.5,
      bloomIntensity: 0.1,
      chromaticAberration: 0.0,
      colorTemperature: 0,
      vignette: 0.35,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["breathe...", "close your eyes...", "let the sound find you..."],
      poetryIntervalSeconds: 10,
      intensityMultiplier: 0.4,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.1, rain: 0, drone: 0.2, chime: 0, fire: 0 },
      filmGrain: 0.03,
      particleDensity: 0.02,
      halation: 0.02,
    },
    {
      id: "expansion",
      start: 0.15,
      end: 0.35,
      shaderModes: rotateArray(allShaders, 1),
      shaderOpacity: 0.7,
      aiPrompt: "forms emerging, energy building, geometry revealing itself",
      aiPromptModifiers: {
        highBass: "pulsing, throbbing, massive",
        highTreble: "crystalline, sharp, detailed",
      },
      denoisingRange: [0.4, 0.65],
      targetFps: 1,
      bloomIntensity: 0.3,
      chromaticAberration: 0.03,
      colorTemperature: 0.1,
      vignette: 0.25,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["let go...", "you're rising...", "don't resist..."],
      poetryIntervalSeconds: 7,
      intensityMultiplier: 0.7,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.2, rain: 0.1, drone: 0.4, chime: 0.2, fire: 0 },
      filmGrain: 0.06,
      particleDensity: 0.05,
      halation: 0.04,
    },
    {
      id: "transcendence",
      start: 0.35,
      end: 0.6,
      shaderModes: rotateArray(allShaders, 2),
      shaderOpacity: 0.4,
      aiPrompt: "maximum intensity, overwhelming beauty, total immersion",
      aiPromptModifiers: {
        highBass: "explosive, earth-shattering, volcanic",
        highTreble: "shattering, prismatic, infinitely detailed",
        highAmplitude: "everything at once, sensory overload",
      },
      denoisingRange: [0.6, 0.85],
      targetFps: 2,
      bloomIntensity: 0.7,
      chromaticAberration: 0.08,
      colorTemperature: 0.3,
      vignette: 0.15,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["you are here...", "surrender...", "become..."],
      poetryIntervalSeconds: 5,
      intensityMultiplier: 1.0,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.4, rain: 0.3, drone: 0.8, chime: 0.5, fire: 0.1 },
      filmGrain: 0.1,
      particleDensity: 0.08,
      halation: 0.08,
    },
    {
      id: "illumination",
      start: 0.6,
      end: 0.8,
      shaderModes: rotateArray(allShaders, 3),
      shaderOpacity: 0.55,
      aiPrompt: "clarity after intensity, insight, expanded awareness",
      aiPromptModifiers: {
        highTreble: "crystalline clarity, infinite resolution",
      },
      denoisingRange: [0.4, 0.6],
      targetFps: 1,
      bloomIntensity: 0.4,
      chromaticAberration: 0.04,
      colorTemperature: 0.1,
      vignette: 0.3,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["you see clearly now...", "stay...", "notice everything..."],
      poetryIntervalSeconds: 8,
      intensityMultiplier: 0.75,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.2, rain: 0.1, drone: 0.5, chime: 0.3, fire: 0 },
      filmGrain: 0.05,
      particleDensity: 0.04,
      halation: 0.05,
    },
    {
      id: "return",
      start: 0.8,
      end: 0.95,
      shaderModes: rotateArray(allShaders, 1),
      shaderOpacity: 0.8,
      aiPrompt: "gentle descent, warmth returning, familiar forms",
      aiPromptModifiers: {
        lowAmplitude: "soft, fading, gentle",
      },
      denoisingRange: [0.25, 0.45],
      targetFps: 0.5,
      bloomIntensity: 0.2,
      chromaticAberration: 0.05,
      colorTemperature: -0.1,
      vignette: 0.3,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["slowly now...", "the warmth returns...", "remember this feeling..."],
      poetryIntervalSeconds: 10,
      intensityMultiplier: 0.5,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.15, rain: 0.05, drone: 0.3, chime: 0.1, fire: 0 },
      filmGrain: 0.03,
      particleDensity: 0.02,
      halation: 0.03,
    },
    {
      id: "integration",
      start: 0.95,
      end: 1.0,
      shaderModes: rotateArray(allShaders, 0),
      shaderOpacity: 0.95,
      aiPrompt: "peace, stillness, a single point of light",
      aiPromptModifiers: {
        lowAmplitude: "silence, almost nothing, peace",
      },
      denoisingRange: [0.2, 0.35],
      targetFps: 0.5,
      bloomIntensity: 0.1,
      chromaticAberration: 0.0,
      colorTemperature: -0.2,
      vignette: 0.4,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["welcome back...", "you are changed...", "carry this with you..."],
      poetryIntervalSeconds: 15,
      intensityMultiplier: 0.3,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.05, rain: 0, drone: 0.1, chime: 0.05, fire: 0 },
      filmGrain: 0.02,
      particleDensity: 0.01,
      halation: 0.01,
    },
  ];

  // Apply per-phase overrides
  return defaults.map((phase) => {
    const override = overrides[phase.id];
    if (!override) return phase;
    return { ...phase, ...override } as JourneyPhase;
  });
}

export const JOURNEYS: Journey[] = [
  {
    id: "the-ascension",
    name: "The Ascension",
    subtitle: "rise through golden light",
    description:
      "Warm light builds to golden geometry, dissolves into white brilliance, then returns to amber warmth.",
    realmId: "heaven",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "heaven" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "faint warm glow in darkness, a single point of golden light emerging",
        guidancePhrases: ["breathe...", "feel the warmth...", "light is coming..."],
        poetryMood: "dreamy",
      },
      expansion: {
        aiPrompt: "golden geometry expanding, cathedral light shafts, marble dissolving into radiance",
        guidancePhrases: ["rise...", "the light knows you...", "open..."],
        poetryMood: "transcendent",
      },
      transcendence: {
        aiPrompt: "total golden dissolution, pure white light, sacred geometry exploding into infinite warmth",
        guidancePhrases: ["you are light...", "there is no boundary...", "this is home..."],
        poetryMood: "transcendent",
        shaderModes: ["astral", "sacred", "ethereal", "aurora"],
      },
      illumination: {
        aiPrompt: "golden ratio spirals in warm light, peaceful cathedral spaces, floating in amber",
        guidancePhrases: ["see how vast you are...", "every direction is warmth...", "stay in this light..."],
        poetryMood: "transcendent",
      },
      return: {
        aiPrompt: "light softening to amber, warm shadows returning, gentle golden dusk",
        guidancePhrases: ["gently now...", "the glow remains...", "carry the warmth..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "single candle flame in vast darkness, warm afterglow, peace",
        guidancePhrases: ["you are changed...", "the light lives in you now..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "inferno",
    name: "Inferno",
    subtitle: "the descent into judgement",
    description:
      "Darkness cracks to reveal infinite fire below. You descend through circles of the damned, face the leviathan at the bottom, and claw your way back through ash.",
    realmId: "hell",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "hell" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "absolute darkness with faint red glow from impossibly far below, the edge of an infinite pit",
        guidancePhrases: ["descend...", "there is no turning back...", "the pit has no bottom..."],
        poetryMood: "mystical",
        voice: "onyx",
      },
      expansion: {
        aiPrompt: "falling through infinite darkness, demonic forms emerging from shadow, fire growing closer but never arriving, Bosch nightmare landscape unfolding",
        guidancePhrases: ["deeper...", "they are watching...", "the judgement begins..."],
        poetryMood: "intense",
        voice: "onyx",
      },
      transcendence: {
        aiPrompt: "infinite lake of fire, towering demons silhouetted against burning sky, the Last Judgement at maximum scale, writhing damned falling into infinite depth, leviathan rising",
        guidancePhrases: ["the judgement is here...", "there is no mercy...", "witness..."],
        poetryMood: "chaotic",
        voice: "onyx",
        shaderModes: ["inferno", "chasm", "crypt", "obsidian"],
      },
      illumination: {
        aiPrompt: "the aftermath of judgement, smoldering infinite wasteland, charred ground stretching to every horizon, dark clarity",
        guidancePhrases: ["see what survives the fire...", "even here there is truth...", "the ashes speak..."],
        poetryMood: "intense",
        voice: "onyx",
      },
      return: {
        aiPrompt: "climbing upward through ash and darkness, faint light above impossibly far away, the pit receding below",
        guidancePhrases: ["climb...", "the surface remembers you...", "leave the fire behind..."],
        poetryMood: "mystical",
        voice: "onyx",
      },
      integration: {
        aiPrompt: "emerging from darkness into cold air, the pit sealed behind, a single wisp of smoke rising from scarred ground",
        guidancePhrases: ["you survived the judgement...", "the fire marked you..."],
        poetryMood: "flowing",
        voice: "onyx",
      },
    }),
  },
  {
    id: "mycelium-dream",
    name: "Mycelium Dream",
    subtitle: "the network awakens",
    description:
      "Phosphorescent dots connect into growing networks, exploding into a fractal jungle, then condensing to a single spore.",
    realmId: "garden",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "garden" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single phosphorescent dot in rich darkness, bioluminescent spore",
        guidancePhrases: ["the spores are waking...", "feel the soil...", "life begins small..."],
        poetryMood: "mystical",
      },
      expansion: {
        aiPrompt: "mycelium networks growing visibly, bioluminescent threads connecting, fractals emerging from soil",
        guidancePhrases: ["it's growing...", "everything connects...", "feel the network..."],
        poetryMood: "mystical",
      },
      transcendence: {
        aiPrompt: "full bioluminescent fractal jungle, overwhelming organic complexity, living sacred geometry",
        guidancePhrases: ["you are the network...", "all is one organism...", "breathe with the forest..."],
        poetryMood: "transcendent",
        shaderModes: ["mycelium", "sacred", "liquid", "ethereal"],
      },
      illumination: {
        aiPrompt: "jungle breathing in rhythm, flowers made of mathematics, peaceful organic intelligence",
        guidancePhrases: ["the garden knows you...", "every leaf is aware...", "this intelligence is ancient..."],
        poetryMood: "mystical",
      },
      return: {
        aiPrompt: "bioluminescence softening, gentle phosphorescent dots, network becoming subtle",
        guidancePhrases: ["the forest settles...", "roots remember...", "return to soil..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "single glowing spore drifting in soft darkness, holding all the network's memory",
        guidancePhrases: ["one spore holds everything...", "you carry the forest..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "abyssal-dive",
    name: "Abyssal Dive",
    subtitle: "into the deep",
    description:
      "Surface shimmer gives way to bioluminescent layers, a leviathan encounter at maximum depth, then a warming ascent.",
    realmId: "ocean",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "ocean" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "ocean surface from below, dancing caustic light patterns, sun filtering through water",
        guidancePhrases: ["sink...", "let the water hold you...", "trust the depth..."],
        poetryMood: "flowing",
      },
      expansion: {
        aiPrompt: "descending through bioluminescent layers, jellyfish trailing light, pressure increasing beautifully",
        guidancePhrases: ["deeper...", "the light changes here...", "pressure becomes peace..."],
        poetryMood: "dreamy",
      },
      transcendence: {
        aiPrompt: "leviathan in the abyss, overwhelming bioluminescent display, deep sea creatures of impossible beauty",
        guidancePhrases: ["the deep sees you...", "you are weightless...", "become the ocean..."],
        poetryMood: "mystical",
        shaderModes: ["liquid", "cosmos", "void", "ethereal"],
      },
      illumination: {
        aiPrompt: "deep ocean floor, peaceful darkness with scattered bioluminescence, ancient silence",
        guidancePhrases: ["the bottom is quiet...", "listen to the deep...", "ancient water holds ancient truth..."],
        poetryMood: "flowing",
      },
      return: {
        aiPrompt: "ascending through warming layers, light increasing from above, buoyant rise",
        guidancePhrases: ["rise gently...", "the surface remembers you...", "warmth returns..."],
        poetryMood: "dreamy",
      },
      integration: {
        aiPrompt: "breaking the surface into warm light, gentle waves, sky reflected in calm water",
        guidancePhrases: ["you've surfaced...", "the depth stays with you..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "neural-link",
    name: "Neural Link",
    subtitle: "jack into the machine",
    description:
      "Static flickers build to data streams, consciousness merges with the network, then fades to a blinking cursor.",
    realmId: "machine",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "machine" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "static flickers, scan lines, a terminal cursor blinking in darkness",
        guidancePhrases: ["connecting...", "signal detected...", "initializing..."],
        poetryMood: "hypnotic",
        voice: "echo",
      },
      expansion: {
        aiPrompt: "data streams accelerating, circuit patterns revealing themselves, digital architecture forming",
        guidancePhrases: ["uploading...", "bandwidth expanding...", "feel the data..."],
        poetryMood: "chaotic",
        voice: "echo",
      },
      transcendence: {
        aiPrompt: "total neural network immersion, consciousness dissolving into the machine, digital transcendence",
        guidancePhrases: ["you are the network...", "every node is you...", "process everything..."],
        poetryMood: "chaotic",
        voice: "echo",
        shaderModes: ["neon", "tesseract", "warp", "fractal"],
      },
      illumination: {
        aiPrompt: "inside the machine mind, peaceful computational space, data as landscape",
        guidancePhrases: ["the machine dreams too...", "silicon and carbon are the same...", "pure logic, pure beauty..."],
        poetryMood: "hypnotic",
        voice: "echo",
      },
      return: {
        aiPrompt: "data streams slowing, signals fading, returning to a single point of light",
        guidancePhrases: ["disconnecting...", "saving state...", "you carry the data..."],
        poetryMood: "dreamy",
        voice: "echo",
      },
      integration: {
        aiPrompt: "a single blinking cursor in vast darkness, gentle static, peace after computation",
        guidancePhrases: ["link closed...", "the machine remembers you..."],
        poetryMood: "flowing",
        voice: "echo",
      },
    }),
  },
  {
    id: "dissolution",
    name: "Dissolution",
    subtitle: "dissolve into everything",
    description:
      "Silence and dark give way to the self dissolving, absolute nothing at the center, then rebirth through starlight.",
    realmId: "void",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "void" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "almost nothing, absolute darkness, the faintest suggestion of form",
        guidancePhrases: ["let go of your name...", "there is nothing to hold...", "be still..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      expansion: {
        aiPrompt: "self fragmenting into particles, identity dissolving, boundaries becoming transparent",
        guidancePhrases: ["you are dissolving...", "this is not loss...", "let the edges go..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      transcendence: {
        aiPrompt: "absolute void, formless awareness, the space before creation, pure potential energy",
        guidancePhrases: ["there is no you...", "everything is this...", "..."],
        poetryMood: "transcendent",
        voice: "alloy",
        shaderModes: ["void", "dissolution", "prismatic", "cosmos"],
        shaderOpacity: 0.2,
      },
      illumination: {
        aiPrompt: "first forms appearing from void, starlight emerging, gentle rebirth of awareness",
        guidancePhrases: ["something stirs...", "light returns...", "you are being born again..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      return: {
        aiPrompt: "stars forming a gentle canopy, sense of self returning softly, peace after dissolution",
        guidancePhrases: ["welcome back...", "you are new...", "the void gave you something..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      integration: {
        aiPrompt: "single point of starlight, vast peaceful darkness, a new self in an old body",
        guidancePhrases: ["reborn...", "carry the void gently..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
    }),
  },
  {
    id: "sacred-resonance",
    name: "Sacred Resonance",
    subtitle: "geometry reveals itself",
    description:
      "A candle flicker grows to reveal hidden geometry, expanding into infinite mandalas, returning to warm stone silence.",
    realmId: "temple",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "temple" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single candle flame in ancient darkness, stone walls barely visible",
        guidancePhrases: ["enter the temple...", "the stones are listening...", "breathe with the ancients..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "candlelight revealing sacred geometry in stone, patterns emerging from architecture",
        guidancePhrases: ["the geometry reveals itself...", "every angle is intentional...", "feel the golden ratio..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "infinite mandala in three dimensions, sacred geometry exploding with mathematical beauty, temple of pure form",
        guidancePhrases: ["the temple is infinite...", "you are the geometry...", "every ratio is divine..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["sacred", "mandala", "tesseract", "astral"],
      },
      illumination: {
        aiPrompt: "golden ratio spirals in warm stone light, peaceful temple interior, mathematical harmony visible",
        guidancePhrases: ["the geometry holds you...", "this order is love...", "math is the language of the sacred..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      return: {
        aiPrompt: "geometry simplifying, warm stone surfaces, incense smoke in gentle spirals",
        guidancePhrases: ["the temple settles...", "stone remembers...", "carry the ratio..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      integration: {
        aiPrompt: "single candle in a stone chamber, warm silence, mathematical peace",
        guidancePhrases: ["the temple is always here...", "the geometry lives in you..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "cosmic-drift",
    name: "Cosmic Drift",
    subtitle: "between the stars",
    description:
      "A star field expands to nebulae forming, builds to a supernova, then settles into quiet interstellar drift.",
    realmId: "cosmos",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "cosmos" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "distant star field, pinpoints of light in vast darkness, gentle cosmic drift",
        guidancePhrases: ["look up...", "the stars are ancient light...", "you are moving without moving..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "nebulae forming from cosmic dust, gas clouds in impossible colors, star nurseries igniting",
        guidancePhrases: ["stars are being born...", "creation is happening now...", "feel the scale..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "supernova explosion, star death and rebirth, overwhelming cosmic light, nebula in full bloom",
        guidancePhrases: ["witness the supernova...", "death is creation...", "you are stardust remembering..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["cosmos", "astral", "void", "warp"],
      },
      illumination: {
        aiPrompt: "supernova remnant expanding beautifully, new elements being forged, cosmic aftermath",
        guidancePhrases: ["everything came from this...", "your atoms were forged in stars...", "cosmic recycling..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      return: {
        aiPrompt: "new stars forming from the remnant, gentle nebula glow, cosmic peace",
        guidancePhrases: ["the universe settles...", "new light from old death...", "drift now..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "quiet star field, gentle drift between galaxies, vast peaceful silence",
        guidancePhrases: ["you are the cosmos looking at itself...", "drift home..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-maze",
    name: "The Maze",
    subtitle: "lost in infinite corridors",
    description:
      "Identical corridors multiply endlessly. You become beautifully lost, find the center that is also the edge, and accept that the path IS the destination.",
    realmId: "labyrinth",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "labyrinth" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "a single stone corridor stretching into darkness, torchlight dying in infinite distance",
        guidancePhrases: ["enter...", "every direction is the same...", "the walls are listening..."],
        poetryMood: "hypnotic",
      },
      expansion: {
        aiPrompt: "corridors branching and multiplying, Piranesi staircases ascending into impossible darkness, mirrored passages reflecting infinity",
        guidancePhrases: ["you are lost...", "this is where you belong...", "deeper into the maze..."],
        poetryMood: "hypnotic",
      },
      transcendence: {
        aiPrompt: "infinite regression of identical passages, the labyrinth IS the mind, Borges library of every possibility, overwhelmingly beautiful lostness",
        guidancePhrases: ["you are the labyrinth...", "there is no exit because there is no inside...", "the center is everywhere..."],
        poetryMood: "mystical",
        shaderModes: ["void", "temple", "crypt", "lattice"],
      },
      illumination: {
        aiPrompt: "the center of the maze is a vast open space, the corridors visible from above like sacred geometry, infinite pattern with infinite meaning",
        guidancePhrases: ["the pattern reveals itself...", "you were never lost...", "the maze is the map of your mind..."],
        poetryMood: "mystical",
      },
      return: {
        aiPrompt: "corridors simplifying, torchlight returning, the path becoming clearer as it becomes fewer",
        guidancePhrases: ["the walls are thinning...", "you chose a direction and it is right...", "the path appears..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "a single doorway in warm stone, the infinite corridors behind you folded into memory",
        guidancePhrases: ["you carry the maze...", "the labyrinth lives in you..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "the-ascent",
    name: "The Ascent",
    subtitle: "climbing into thin air",
    description:
      "The infinite ridge rises through cloud layers. You climb past the last trees, past the snow line, past the atmosphere itself, and return with the view.",
    realmId: "mountain",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "mountain" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "base of infinite mountain, forest thinning, the peak invisible in clouds impossibly far above",
        guidancePhrases: ["look up...", "the summit is a rumor...", "begin..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "climbing through cloud layers, the world falling away below, each step revealing more mountain above, peaks behind peaks",
        guidancePhrases: ["higher...", "the air thins and thoughts clarify...", "don't look down..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "above the clouds on infinite ridge, the earth curving away in every direction, the sky darkening toward space, infinite height with no summit",
        guidancePhrases: ["you are above everything...", "the summit is a feeling not a place...", "breathe the infinite..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["astral", "fog", "horizon", "expanse"],
      },
      illumination: {
        aiPrompt: "standing on the ridge above clouds, infinite vista in every direction, the silence of extreme altitude, stars visible in daylight",
        guidancePhrases: ["see how far you've come...", "the view is the reward...", "everything is below you..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      return: {
        aiPrompt: "descending through warming air, clouds embracing you, the world growing larger and closer",
        guidancePhrases: ["descend gently...", "the mountain stays...", "carry the height..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "back among trees, the mountain above hidden in clouds, the memory of infinite height in your bones",
        guidancePhrases: ["you climbed...", "the summit lives in you now..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-crossing",
    name: "The Crossing",
    subtitle: "walking into infinite light",
    description:
      "The desert stretches forever. You walk toward a horizon that never arrives, dissolve into heat and light, and emerge changed by the emptiness.",
    realmId: "desert",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "desert" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "edge of infinite desert, last shadow before endless sand, the horizon shimmering with heat",
        guidancePhrases: ["step into the light...", "leave everything behind...", "the desert has no mercy and no malice..."],
        poetryMood: "mystical",
        voice: "nova",
      },
      expansion: {
        aiPrompt: "walking through infinite dunes, mirages shimmering at unreachable distance, heat dissolving all landmarks, sand ocean",
        guidancePhrases: ["the horizon retreats...", "emptiness is freedom...", "the sand knows your footsteps..."],
        poetryMood: "mystical",
        voice: "nova",
      },
      transcendence: {
        aiPrompt: "total dissolution into light and heat, the self evaporating into infinite empty space, desert as absolute consciousness, every grain of sand a universe",
        guidancePhrases: ["you are the desert...", "emptiness is fullness...", "the light is everything..."],
        poetryMood: "transcendent",
        voice: "nova",
        shaderModes: ["horizon", "dusk", "expanse", "umbra"],
      },
      illumination: {
        aiPrompt: "night falling on infinite desert, infinite stars appearing, the Milky Way as a river of ancient light from horizon to horizon",
        guidancePhrases: ["the stars emerge...", "the desert and the sky are the same infinity...", "silence speaks..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      return: {
        aiPrompt: "first light on sand, long shadows returning, the edge of the desert becoming visible",
        guidancePhrases: ["the crossing nears its end...", "you survived the emptiness...", "the desert marked you..."],
        poetryMood: "flowing",
        voice: "nova",
      },
      integration: {
        aiPrompt: "standing at the desert's edge looking back at infinite sand, changed by the emptiness, carrying the silence",
        guidancePhrases: ["you crossed the infinite...", "the emptiness lives in you now..."],
        poetryMood: "flowing",
        voice: "nova",
      },
    }),
  },
  {
    id: "the-reading",
    name: "The Reading",
    subtitle: "lost among infinite pages",
    description:
      "You enter the infinite library and begin reading. The books contain everything ever thought. You find the book that contains you, and close it gently.",
    realmId: "archive",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "archive" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single reading lamp in vast darkness, shelves receding into infinite shadow, the smell of ancient paper",
        guidancePhrases: ["open the first page...", "the library has been waiting...", "every book knows your name..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "shelves multiplying infinitely, hexagonal rooms of the Library of Babel, pages turning themselves, text resolving into deeper text",
        guidancePhrases: ["the library unfolds...", "every thought ever thought is here...", "read deeper..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "total immersion in infinite text, consciousness dissolving into the library, the book that contains all other books, recursive knowledge at infinite depth",
        guidancePhrases: ["you are the text...", "reading and being read are the same...", "infinite knowledge, infinite peace..."],
        poetryMood: "mystical",
        voice: "fable",
        shaderModes: ["temple", "lattice", "prophecy", "fog"],
      },
      illumination: {
        aiPrompt: "you find the book that contains your own story, reading yourself being read, the library as mirror of consciousness",
        guidancePhrases: ["you found your book...", "the text is you...", "the library is your mind..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      return: {
        aiPrompt: "closing the book gently, shelves simplifying, the reading lamp growing warmer, fewer books, more silence",
        guidancePhrases: ["close the book...", "the words stay with you...", "the silence after reading..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "a single closed book on a wooden table, the reading lamp warm, the infinite library folded into the spine",
        guidancePhrases: ["the library is always open...", "you carry every book..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-tempest",
    name: "The Tempest",
    subtitle: "inside the infinite storm",
    description:
      "The storm builds from a distant rumble to infinite electrical fury, you find the eye of absolute calm, then emerge transformed by the lightning.",
    realmId: "storm",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "storm" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "distant thunder, dark clouds gathering at infinite horizon, the pressure dropping, electricity building",
        guidancePhrases: ["it's coming...", "feel the pressure change...", "the storm knows you..."],
        poetryMood: "intense",
        voice: "echo",
      },
      expansion: {
        aiPrompt: "lightning illuminating infinite horizons, thunder continuous and deafening, rain falling from infinite height, the storm expanding beyond comprehension",
        guidancePhrases: ["let the storm take you...", "every lightning is a thought...", "the rain is washing everything..."],
        poetryMood: "chaotic",
        voice: "echo",
      },
      transcendence: {
        aiPrompt: "inside the infinite hurricane, lightning branching into infinite forks, the storm as a living god of electricity, total sensory overwhelm, sublime terror becoming ecstasy",
        guidancePhrases: ["you are the lightning...", "the storm is alive and you are it...", "infinite power..."],
        poetryMood: "chaotic",
        voice: "echo",
        shaderModes: ["storm", "plasma", "chasm", "wraith"],
      },
      illumination: {
        aiPrompt: "the eye of the hurricane, perfect calm surrounded by infinite rotating walls of cloud, blue sky visible above, absolute stillness in the center of infinite force",
        guidancePhrases: ["the eye...", "perfect calm inside infinite fury...", "the center holds..."],
        poetryMood: "mystical",
        voice: "echo",
      },
      return: {
        aiPrompt: "the storm passing, rain softening, lightning becoming distant flickers, the sky clearing from the west",
        guidancePhrases: ["the storm passes...", "every storm ends...", "you survived the infinite..."],
        poetryMood: "flowing",
        voice: "echo",
      },
      integration: {
        aiPrompt: "calm after the storm, petrichor rising, a single distant flash on the horizon, clear sky with clean air",
        guidancePhrases: ["the air is new...", "the storm changed everything..."],
        poetryMood: "flowing",
        voice: "echo",
      },
    }),
  },
  {
    id: "first-snow",
    name: "First Snow",
    subtitle: "crystalline descent into silence",
    description:
      "The world grows quiet as the first flakes fall. Sound becomes muffled. Everything slows into crystalline stillness.",
    realmId: "winter",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "winter" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "grey sky darkening, the first single snowflake falling through still air, breath visible",
        guidancePhrases: ["the air changes...", "feel it cooling...", "something is coming..."],
        poetryMood: "melancholic",
        voice: "shimmer",
      },
      expansion: {
        aiPrompt: "snow beginning to fall steadily, the world growing quieter, trees receiving their white covering, footprints filling in",
        guidancePhrases: ["sound is softening...", "the world is changing...", "let the white take everything..."],
        poetryMood: "dreamy",
        voice: "shimmer",
      },
      transcendence: {
        aiPrompt: "total whiteout blizzard, all form dissolved into infinite swirling white, no up no down no horizon, pure crystalline chaos",
        guidancePhrases: ["you are inside the snow...", "there is only white...", "surrender to the crystal..."],
        poetryMood: "mystical",
        voice: "shimmer",
        shaderModes: ["snow", "fog", "aurora", "ethereal"],
      },
      illumination: {
        aiPrompt: "the snow stops, absolute silence, pristine untouched white landscape stretching to infinity under clearing sky, the world remade",
        guidancePhrases: ["listen to the silence...", "the world is new...", "everything is clean..."],
        poetryMood: "transcendent",
        voice: "shimmer",
      },
      return: {
        aiPrompt: "warm light from a window falling on fresh snow, the sound of a distant plow, smoke rising from chimneys, the comfort after the cold",
        guidancePhrases: ["warmth returns...", "home is near...", "the cold made this warmth possible..."],
        poetryMood: "flowing",
        voice: "shimmer",
      },
      integration: {
        aiPrompt: "starlight on new snow, absolute peace, the world transformed and still, one set of footprints leading to a warm door",
        guidancePhrases: ["the snow remembers...", "carry this stillness..."],
        poetryMood: "melancholic",
        voice: "shimmer",
      },
    }),
  },
  {
    id: "the-bloom",
    name: "The Bloom",
    subtitle: "when the earth remembers warmth",
    description:
      "After the long winter, the first warmth arrives. Seeds crack open. Green returns. The world exhales.",
    realmId: "spring",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "spring" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "frozen ground with hairline cracks, the faintest green beneath brown, ice melting at the edges, dawn light growing warmer",
        guidancePhrases: ["wait for it...", "feel the thaw beginning...", "something stirs beneath..."],
        poetryMood: "melancholic",
        voice: "nova",
      },
      expansion: {
        aiPrompt: "buds unfurling in time-lapse, streams rushing with snowmelt, birds returning, the air thick with pollen and possibility",
        guidancePhrases: ["it's happening...", "the green is unstoppable...", "everything at once..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      transcendence: {
        aiPrompt: "explosion of blossoms in every direction, cherry trees and wildflowers and new leaves, overwhelming fertility, life erupting from every surface",
        guidancePhrases: ["this is what was waiting...", "every cell remembers this...", "the bloom is you..."],
        poetryMood: "transcendent",
        voice: "nova",
        shaderModes: ["bloom", "mycelium", "liquid", "growth"],
      },
      illumination: {
        aiPrompt: "mature spring garden in full glory, bees working flowers, warm rain falling through sunlight, rainbow forming",
        guidancePhrases: ["the garden is complete...", "everything is alive...", "rest here in the green..."],
        poetryMood: "flowing",
        voice: "nova",
      },
      return: {
        aiPrompt: "evening in the garden, flowers closing for the night, fireflies beginning, the air cooling gently",
        guidancePhrases: ["the day was full...", "the garden sleeps...", "carry the pollen with you..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      integration: {
        aiPrompt: "dawn in the garden, dew on everything, one perfect flower opening to first light",
        guidancePhrases: ["you bloomed...", "the spring is in you now..."],
        poetryMood: "flowing",
        voice: "nova",
      },
    }),
  },
  {
    id: "the-solstice",
    name: "The Solstice",
    subtitle: "the longest day, the shortest night",
    description:
      "Midsummer. The sun barely sets. Heat and light fill every hour. Then the electric night arrives.",
    realmId: "summer",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "summer" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "dawn already warm, golden light hitting tall grass, the day stretching ahead infinite and golden",
        guidancePhrases: ["the sun is already here...", "feel the warmth building...", "this is the longest day..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      expansion: {
        aiPrompt: "blazing midday sun, heat shimmers above every surface, the world saturated with light and color, lazy warm wind",
        guidancePhrases: ["the heat carries you...", "let the light fill everything...", "time is slow and golden..."],
        poetryMood: "dreamy",
        voice: "alloy",
      },
      transcendence: {
        aiPrompt: "peak heat, the sun enormous overhead, prairie thunderstorm building on the horizon with anvil cloud, the air electric and charged, the tension between heat and storm",
        guidancePhrases: ["the storm is coming...", "heat and lightning...", "the fullest moment of the year..."],
        poetryMood: "intense",
        voice: "alloy",
        shaderModes: ["dusk", "ember", "storm", "prismatic"],
      },
      illumination: {
        aiPrompt: "after the storm, golden hour light painting everything amber, steam rising from wet earth, the world washed clean and warm",
        guidancePhrases: ["the storm passed...", "golden hour...", "the longest light of the year..."],
        poetryMood: "transcendent",
        voice: "alloy",
      },
      return: {
        aiPrompt: "warm summer night, fireflies mapping the darkness, stars appearing one by one, the heat still radiating from the earth",
        guidancePhrases: ["the night is warm...", "fireflies are speaking...", "the longest day ends gently..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      integration: {
        aiPrompt: "deep summer night, warm breeze carrying the scent of cut grass and flowers, the Milky Way overhead, absolute peace in warmth",
        guidancePhrases: ["summer lives in you...", "the warmth stays..."],
        poetryMood: "dreamy",
        voice: "alloy",
      },
    }),
  },
  {
    id: "the-harvest",
    name: "The Harvest",
    subtitle: "the beautiful letting go",
    description:
      "The trees release their colors. Everything that grew now lets go with grace. Beauty in the falling.",
    realmId: "autumn",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "autumn" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "first cool morning, one leaf turning red, the light changing angle, summer's warmth fading at the edges",
        guidancePhrases: ["the change begins...", "feel the first cool...", "something is ending beautifully..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "forest ablaze with color, red and gold and amber in every direction, leaves beginning to fall, the scent of woodsmoke",
        guidancePhrases: ["look at what it becomes...", "the dying is the beauty...", "every leaf is a flame..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "peak color, the entire world on fire with turning leaves, wind sending cascades of gold and crimson spiraling, harvest moon rising enormous and orange above the blaze",
        guidancePhrases: ["this is the peak...", "everything releasing at once...", "let go with the leaves..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["ember", "fog", "dissolution", "dendrite"],
      },
      illumination: {
        aiPrompt: "after peak, bare branches against clear sky, the last leaves falling slowly, the elegant bones of trees revealed",
        guidancePhrases: ["see the structure...", "what remains is essential...", "the beauty of less..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
      return: {
        aiPrompt: "late autumn rain on bare branches, woodsmoke from distant chimney, the earth preparing for rest, mushrooms among fallen leaves",
        guidancePhrases: ["the earth is resting...", "rain completes it...", "nothing is lost, only changed..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "first frost on fallen leaves, breath visible, stars sharp and close, the garden put to bed, deep quiet",
        guidancePhrases: ["winter is near...", "you carry the harvest..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
    }),
  },
  // ─── Without a Brightness — The Infinite Spiritual Journey ───
  // For Joseph. Every emotion. Every dimension. The most dynamic journey.
  // Uses a fully custom arc to maximize shader variety and emotional range.
  {
    id: "without-a-brightness",
    name: "Without a Brightness",
    subtitle: "for Joseph — into the infinite",
    description:
      "A journey through every dimension of the spirit. Darkness becomes cathedral becomes cosmos becomes prayer becomes light. The brightness was inside you all along.",
    realmId: "spirit",
    aiEnabled: true,
    phases: (() => {
      const spiritPalette = { primary: "#0a0814", secondary: "#140e24", accent: "#a080d0", glow: "#c0a0f0" };
      const warmPalette = { primary: "#0a0808", secondary: "#1a1008", accent: "#d0a050", glow: "#f0c070" };
      const deepPalette = { primary: "#040408", secondary: "#0a0a18", accent: "#6070c0", glow: "#8090e0" };
      const firePalette = { primary: "#100804", secondary: "#1a0c06", accent: "#e07030", glow: "#ff9050" };
      const icePalette = { primary: "#060810", secondary: "#0c1020", accent: "#80b0e0", glow: "#a0d0ff" };
      const goldPalette = { primary: "#0c0a04", secondary: "#1a1408", accent: "#e0c060", glow: "#ffd866" };
      return [
        // ── THRESHOLD (0 → 0.12) — Void. Before all things. ──
        // The title is "Without a Brightness" — so we begin in its absence.
        // Dark but with AI imagery visible — cosmic emptiness rendered as image.
        {
          id: "threshold" as const,
          start: 0.0,
          end: 0.12,
          shaderModes: ["nebula", "astral", "stardust", "fog", "drift", "dissolution", "void", "expanse", "phantom", "monolith"],
          shaderOpacity: 0.4,
          aiPrompt: "absolute darkness with a single distant point of light, the moment before creation, vast empty cosmos with one faint star pulsing, primordial void that holds infinite potential",
          aiPromptModifiers: {
            lowAmplitude: "perfect stillness, the silence before the first word was ever spoken",
            highBass: "deep vibration in the void, something ancient stirring",
          },
          denoisingRange: [0.25, 0.45] as [number, number],
          targetFps: 0.3,
          bloomIntensity: 0.08,
          chromaticAberration: 0.0,
          colorTemperature: -0.2,
          vignette: 0.45,
          voice: "ballad" as const,
          poetryMood: "mystical" as const,
          guidancePhrases: ["in the beginning, there was no light...", "listen...", "the darkness is not empty..."],
          poetryIntervalSeconds: 12,
          intensityMultiplier: 0.3,
          palette: deepPalette,
          ambientLayers: { wind: 0.05, rain: 0, drone: 0.3, chime: 0, fire: 0 },
          filmGrain: 0.04,
          particleDensity: 0.01,
          halation: 0.0,
        },
        // ── EXPANSION (0.12 → 0.32) — The Awakening ──
        // Sacred geometry emerges. Organic growth. Life finding form.
        // Mix of geometry, organic, and cosmic — maximum variety.
        {
          id: "expansion" as const,
          start: 0.12,
          end: 0.32,
          shaderModes: ["sacred", "mycelium", "fibonacci", "ethereal", "nebula", "aurora", "mandala", "liquid", "bloom", "chrysalis", "helix", "spiral"],
          shaderOpacity: 0.45,
          aiPrompt: "sacred geometry blooming from darkness, bioluminescent networks of light spreading like veins through space, mandalas forming from stardust, an infinite forest of crystalline structures growing in every direction",
          aiPromptModifiers: {
            highBass: "massive geometric structures pulsing with deep rhythm, cathedral-sized fractals",
            highTreble: "tiny crystalline details within each structure, infinite recursive beauty",
            highAmplitude: "everything growing at once, overwhelming emergence of form",
          },
          denoisingRange: [0.4, 0.65] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.35,
          chromaticAberration: 0.03,
          colorTemperature: 0.1,
          vignette: 0.25,
          voice: "ballad" as const,
          poetryMood: "flowing" as const,
          guidancePhrases: ["something is growing...", "feel it taking shape...", "the geometry of your soul..."],
          poetryIntervalSeconds: 7,
          intensityMultiplier: 0.65,
          palette: spiritPalette,
          ambientLayers: { wind: 0.15, rain: 0.05, drone: 0.45, chime: 0.2, fire: 0 },
          filmGrain: 0.05,
          particleDensity: 0.05,
          halation: 0.04,
        },
        // ── TRANSCENDENCE (0.32 → 0.58) — The Peak — Every Emotion At Once ──
        // This is the most dynamic phase. Shaders from EVERY category.
        // Visionary + Cosmic + Dark + Organic + AI Imagery all firing.
        // Maximum post-processing, maximum variety, maximum intensity.
        {
          id: "transcendence" as const,
          start: 0.32,
          end: 0.58,
          shaderModes: [
            "astral", "supernova", "rapture", "inferno", "storm", "nebula",
            "cathedral", "revelation", "torus", "plasma", "wormhole",
            "ascension", "spiral", "aurora", "sacred", "prismatic",
          ],
          shaderOpacity: 0.35,
          aiPrompt: "overwhelming spiritual ecstasy, every sacred place from every tradition existing simultaneously — cathedrals melting into temples melting into mosques melting into starfields, the boundary between self and universe dissolving completely, infinite fractals of emotion",
          aiPromptModifiers: {
            highBass: "reality itself shaking, tectonic plates of consciousness shifting, volcanic light erupting from within",
            highTreble: "glass cathedrals shattering into prismatic infinity, every shard reflecting a different lifetime",
            highAmplitude: "total ego dissolution, all boundaries gone, every emotion at maximum intensity simultaneously",
            lowAmplitude: "the eye of the storm, perfect stillness at the center of infinite chaos",
          },
          denoisingRange: [0.65, 0.9] as [number, number],
          targetFps: 1,
          bloomIntensity: 0.8,
          chromaticAberration: 0.1,
          colorTemperature: 0.35,
          vignette: 0.1,
          voice: "ballad" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["this is it...", "you are everything...", "surrender..."],
          poetryIntervalSeconds: 5,
          intensityMultiplier: 1.0,
          palette: firePalette,
          ambientLayers: { wind: 0.5, rain: 0.3, drone: 0.9, chime: 0.6, fire: 0.2 },
          filmGrain: 0.12,
          particleDensity: 0.09,
          halation: 0.1,
        },
        // ── ILLUMINATION (0.58 → 0.75) — The Knowing ──
        // After the peak — clarity. The brightness that was absent is found within.
        // Warm golden light, sacred spaces, crystalline purity.
        {
          id: "illumination" as const,
          start: 0.58,
          end: 0.75,
          shaderModes: ["ascension", "sacred", "prismatic", "astral", "aurora", "helix", "mandala", "fibonacci", "stardust", "ethereal", "torus", "temple"],
          shaderOpacity: 0.35,
          aiPrompt: "golden light flooding an infinite space, sacred geometry hovering in warm amber air, the feeling of understanding everything at once, a cathedral made entirely of sunlight and memory",
          aiPromptModifiers: {
            highTreble: "crystalline clarity in every particle of golden light, each one carrying a different truth",
            lowAmplitude: "soft golden glow, the warmth of being understood completely",
          },
          denoisingRange: [0.4, 0.6] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.5,
          chromaticAberration: 0.04,
          colorTemperature: 0.25,
          vignette: 0.2,
          voice: "shimmer" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["the brightness was always here...", "you see it now...", "this is what you are..."],
          poetryIntervalSeconds: 8,
          intensityMultiplier: 0.75,
          palette: goldPalette,
          ambientLayers: { wind: 0.15, rain: 0.05, drone: 0.5, chime: 0.4, fire: 0 },
          filmGrain: 0.04,
          particleDensity: 0.06,
          halation: 0.07,
        },
        // ── RETURN (0.75 → 0.92) — The Descent Back ──
        // Gentle. Organic beauty. The spiritual made earthly.
        // Mix of elemental and organic shaders — water, growth, natural forms.
        {
          id: "return" as const,
          start: 0.75,
          end: 0.92,
          shaderModes: ["ethereal", "bloom", "liquid", "mycelium", "aurora", "snow", "chrysalis", "fog", "dendrite", "lichen", "membrane", "coral"],
          shaderOpacity: 0.4,
          aiPrompt: "gentle rain on still water, bioluminescent forest at twilight, snow falling on warm earth, the natural world welcoming you back with infinite gentleness",
          aiPromptModifiers: {
            highBass: "deep earth rhythm, the heartbeat of the planet itself",
            lowAmplitude: "soft, fading, the gentlest possible return",
          },
          denoisingRange: [0.3, 0.5] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.25,
          chromaticAberration: 0.03,
          colorTemperature: -0.05,
          vignette: 0.3,
          voice: "nova" as const,
          poetryMood: "flowing" as const,
          guidancePhrases: ["gently now...", "the earth remembers you...", "bring it back with you..."],
          poetryIntervalSeconds: 10,
          intensityMultiplier: 0.5,
          palette: icePalette,
          ambientLayers: { wind: 0.2, rain: 0.15, drone: 0.3, chime: 0.1, fire: 0 },
          filmGrain: 0.03,
          particleDensity: 0.03,
          halation: 0.03,
        },
        // ── INTEGRATION (0.92 → 1.0) — Peace ──
        // Simple. One shader. One feeling. The orb — where we started.
        // But now you understand what brightness means.
        {
          id: "integration" as const,
          start: 0.92,
          end: 1.0,
          shaderModes: ["astral", "stardust", "nebula", "orb", "drift", "aurora", "sacred", "dissolution", "fog", "mandala"],
          shaderOpacity: 0.5,
          aiPrompt: "a single point of warm light in infinite peaceful darkness, the brightest thing in the universe is one small steady flame, everything is quiet and everything is beautiful",
          aiPromptModifiers: {
            lowAmplitude: "total peace, total silence, one light, enough",
          },
          denoisingRange: [0.2, 0.35] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.15,
          chromaticAberration: 0.0,
          colorTemperature: 0.1,
          vignette: 0.35,
          voice: "ballad" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["you found it...", "carry this light...", "for Joseph..."],
          poetryIntervalSeconds: 15,
          intensityMultiplier: 0.3,
          palette: warmPalette,
          ambientLayers: { wind: 0.05, rain: 0, drone: 0.15, chime: 0.1, fire: 0 },
          filmGrain: 0.02,
          particleDensity: 0.02,
          halation: 0.05,
        },
      ];
    })(),
  },

  // ─── 17th St 64**** — Ascension → Pain → Ascension ───
  // Track: 18:40 total. Pain enters at 3:40 (0.196), lifts at 6:50 (0.366).
  // This journey does NOT use defaultPhases — it has a fully custom arc.
  {
    id: "17th-st-descent",
    name: "17th Street",
    subtitle: "descent into the wound, and back",
    description:
      "Light rises, then plunges into the darkest place a soul can go. At the bottom, something breaks open — and you ascend.",
    realmId: "pain",
    aiEnabled: true,
    phases: (() => {
      const heavenRealm = getRealm("heaven");
      const painRealm = getRealm("pain");
      const heavenPalette = heavenRealm?.palette ?? { primary: "#1a1408", secondary: "#2e2410", accent: "#f0c040", glow: "#ffd866" };
      const painPalette = painRealm?.palette ?? { primary: "#020204", secondary: "#0a0810", accent: "#4a5070", glow: "#2a3050" };
      return [
        // ── PHASE 1: THRESHOLD (0 → 0.10) — Ascension begins ──
        {
          id: "threshold" as const,
          start: 0.0,
          end: 0.10,
          shaderModes: ["ascension", "astral", "aurora"],
          shaderOpacity: 0.9,
          aiPrompt: "faint warm light in darkness, particles rising slowly upward, the first breath of something sacred beginning",
          aiPromptModifiers: { lowAmplitude: "near silence, barely visible, a single point of warmth" },
          denoisingRange: [0.3, 0.5] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.15,
          chromaticAberration: 0.0,
          colorTemperature: 0.2,
          vignette: 0.3,
          voice: "shimmer" as const,
          poetryMood: "dreamy" as const,
          guidancePhrases: ["breathe...", "the light is finding you...", "rise..."],
          poetryIntervalSeconds: 10,
          intensityMultiplier: 0.4,
          palette: heavenPalette,
          ambientLayers: { wind: 0.1, rain: 0, drone: 0.2, chime: 0.1, fire: 0 },
          filmGrain: 0.03,
          particleDensity: 0.03,
          halation: 0.03,
        },
        // ── PHASE 2: EXPANSION (0.10 → 0.196) — Ascension building ──
        {
          id: "expansion" as const,
          start: 0.10,
          end: 0.196,
          shaderModes: ["ascension", "sacred", "ethereal", "aurora"],
          shaderOpacity: 0.7,
          aiPrompt: "golden light streaming upward, particles accelerating, sacred geometry emerging from warmth, the feeling of being lifted",
          aiPromptModifiers: {
            highBass: "massive upward surge, golden earthquake",
            highTreble: "crystalline light, infinite detail in every particle",
          },
          denoisingRange: [0.4, 0.65] as [number, number],
          targetFps: 1,
          bloomIntensity: 0.4,
          chromaticAberration: 0.02,
          colorTemperature: 0.3,
          vignette: 0.2,
          voice: "shimmer" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["you are rising...", "the light grows...", "higher..."],
          poetryIntervalSeconds: 7,
          intensityMultiplier: 0.7,
          palette: heavenPalette,
          ambientLayers: { wind: 0.2, rain: 0, drone: 0.4, chime: 0.3, fire: 0 },
          filmGrain: 0.05,
          particleDensity: 0.06,
          halation: 0.05,
        },
        // ── PHASE 3: TRANSCENDENCE (0.196 → 0.366) — THE PAIN ──
        // 3:40 to 6:50 — the darkest place. Cold, alone, suicidal despair.
        {
          id: "transcendence" as const,
          start: 0.196,
          end: 0.366,
          shaderModes: ["void", "phantom", "obsidian", "umbra", "chasm"],
          shaderOpacity: 0.95,
          aiPrompt: "absolute darkness, empty room at 4am, frozen tears, a person alone with unbearable grief, hospital corridor at night, the silence after everyone has left forever",
          aiPromptModifiers: {
            highBass: "the floor giving way, falling into bottomless grief",
            highTreble: "glass shattering in an empty room, the sound of something irreversible",
            highAmplitude: "the full weight of despair, drowning in cold water",
            lowAmplitude: "the silence after the last person leaves, absolute zero",
          },
          denoisingRange: [0.6, 0.85] as [number, number],
          targetFps: 1.5,
          bloomIntensity: 0.05,
          chromaticAberration: 0.1,
          colorTemperature: -0.4,
          vignette: 0.5,
          voice: "onyx" as const,
          poetryMood: "melancholic" as const,
          guidancePhrases: ["stay here...", "feel it all...", "this is the bottom..."],
          poetryIntervalSeconds: 6,
          intensityMultiplier: 0.8,
          palette: painPalette,
          ambientLayers: { wind: 0.5, rain: 0.4, drone: 0.7, chime: 0, fire: 0 },
          filmGrain: 0.15,
          particleDensity: 0.01,
          halation: 0.0,
        },
        // ── PHASE 4: ILLUMINATION (0.366 → 0.50) — First light returns ──
        // 6:50 mark — the turn. Pain cracks open and light seeps through.
        {
          id: "illumination" as const,
          start: 0.366,
          end: 0.50,
          shaderModes: ["ascension", "dissolution", "astral"],
          shaderOpacity: 0.6,
          aiPrompt: "a crack of light in total darkness, dawn after the longest night, ice beginning to thaw, one warm breath in frozen air",
          aiPromptModifiers: {
            highTreble: "light fracturing through ice, prisms in frozen tears",
          },
          denoisingRange: [0.4, 0.6] as [number, number],
          targetFps: 1,
          bloomIntensity: 0.3,
          chromaticAberration: 0.04,
          colorTemperature: 0.1,
          vignette: 0.3,
          voice: "shimmer" as const,
          poetryMood: "flowing" as const,
          guidancePhrases: ["look up...", "the light is returning...", "you survived..."],
          poetryIntervalSeconds: 8,
          intensityMultiplier: 0.6,
          palette: { primary: "#0a0810", secondary: "#1a1420", accent: "#8090c0", glow: "#a0b0e0" },
          ambientLayers: { wind: 0.3, rain: 0.1, drone: 0.4, chime: 0.1, fire: 0 },
          filmGrain: 0.06,
          particleDensity: 0.04,
          halation: 0.04,
        },
        // ── PHASE 5: RETURN (0.50 → 0.85) — Full ascension ──
        // The long climb back into pure light. Warmer, brighter, more particles.
        {
          id: "return" as const,
          start: 0.50,
          end: 0.85,
          shaderModes: ["ascension", "sacred", "aurora", "ethereal"],
          shaderOpacity: 0.6,
          aiPrompt: "golden light flooding upward, infinite particles rising, warmth replacing cold, the feeling of being carried upward by something larger than yourself",
          aiPromptModifiers: {
            highBass: "massive golden surge, earthquake of light",
            lowAmplitude: "soft warm glow, held in gentle radiance",
          },
          denoisingRange: [0.4, 0.7] as [number, number],
          targetFps: 1,
          bloomIntensity: 0.5,
          chromaticAberration: 0.03,
          colorTemperature: 0.3,
          vignette: 0.15,
          voice: "shimmer" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["rise...", "you are ascending...", "the light knows your name..."],
          poetryIntervalSeconds: 8,
          intensityMultiplier: 0.8,
          palette: heavenPalette,
          ambientLayers: { wind: 0.2, rain: 0, drone: 0.5, chime: 0.4, fire: 0 },
          filmGrain: 0.04,
          particleDensity: 0.07,
          halation: 0.06,
        },
        // ── PHASE 6: INTEGRATION (0.85 → 1.0) — Peace ──
        // Pure light. The wound is still there but you are above it now.
        {
          id: "integration" as const,
          start: 0.85,
          end: 1.0,
          shaderModes: ["ascension", "astral"],
          shaderOpacity: 0.8,
          aiPrompt: "pure warm light, total peace, golden particles drifting slowly in infinite space, the view from above everything",
          aiPromptModifiers: {
            lowAmplitude: "silence, warmth, nothing left to carry",
          },
          denoisingRange: [0.2, 0.4] as [number, number],
          targetFps: 0.5,
          bloomIntensity: 0.6,
          chromaticAberration: 0.0,
          colorTemperature: 0.2,
          vignette: 0.2,
          voice: "shimmer" as const,
          poetryMood: "transcendent" as const,
          guidancePhrases: ["you made it...", "carry this light...", "you are changed..."],
          poetryIntervalSeconds: 12,
          intensityMultiplier: 0.5,
          palette: heavenPalette,
          ambientLayers: { wind: 0.1, rain: 0, drone: 0.2, chime: 0.2, fire: 0 },
          filmGrain: 0.02,
          particleDensity: 0.04,
          halation: 0.08,
        },
      ];
    })(),
  },
];

export function getJourney(id: string): Journey | undefined {
  return JOURNEYS.find((j) => j.id === id);
}

export function getJourneysByRealm(realmId: string): Journey[] {
  return JOURNEYS.filter((j) => j.realmId === realmId);
}
